apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses:
    -  10.0.0.251-10.0.0.251 # 1 IP node
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool
