
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonplaceholder
  namespace: microservice-dev
  labels:
    app: jsonplaceholder
spec:
  selector:
    matchLabels:
      app: jsonplaceholder
  template:
    metadata:
      labels:
        app: jsonplaceholder
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: jsonplaceholder
          image: svenwal/jsonplaceholder
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: microservice-dev
  labels:
    app: jsonplaceholder
spec:
  selector:
    app: jsonplaceholder
  ports:
    - name: jsonplaceholder
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jsonplaceholder-hpa
  namespace: microservice-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jsonplaceholder
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
