name: GO build app
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
      tag:
        description: 'Tag or version'
        required: true
        default: 'v0.1.0'
  push:
    branches:
      - main
env:
  REPO_NAME: 'go-portfolio-api'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*

      - name: Build app...
        run: |
          GOOS=linux GOARCH=amd64 GOMAXPROCS=1 go build -o ${{ env.REPO_NAME }}-app ./cmd/server/main.go

      - name: List files
        run: |
          ls -la

      - name: Create archive app
        run: |
          zip ${{ env.REPO_NAME }}-app.zip ${{ env.REPO_NAME }}-app
          echo "Created ${{ env.REPO_NAME }}-app.zip"
    
      - name: Upload app to github packages
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ vars.USERNAME }}/${{ env.REPO_NAME }}
          files: ${{ env.REPO_NAME }}-app.zip
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag_name: ${{ inputs.tag }}