name: Create Server User For App
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Server name to setup'
        required: true
        type: choice
        default: 'Back-End-Server'
        options:
          - 'Back-End-Server'
          - 'Front-End-Server'
      username:
        description: 'Username to create'
        required: true
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up runner workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*

      - name: Execute command on Back-End Server
        uses: appleboy/ssh-action@v1.0.3
        if: ${{ inputs.server_name == 'Back-End-Server' }}
        with:
          host: ${{ secrets.BACKEND_SERVER_HOST }}
          username: ${{ secrets.BACKEND_SERVER_USERNAME }}
          key: ${{ secrets.BACKEND_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.BACKEND_SERVER_PORT }}
          script: |
            if [ "$EUID" -ne 0 ]; then
              echo "must run with root"
              exit 1
            fi

      - name: Execute command on Back-End Server
        uses: appleboy/ssh-action@v1.0.3
        if: ${{ inputs.server_name == 'Front-End-Server' }}
        with:
          host: ${{ secrets.FRONTEND_SERVER_HOST }}
          username: ${{ secrets.FRONTEND_SERVER_USERNAME }}
          key: ${{ secrets.FRONTEND_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.FRONTEND_SERVER_PORT }}
          script: |
            if [ "$EUID" -ne 0 ]; then
              echo "must run with root"
              exit 1
            fi

      - name: Clean up runner workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
    