name: GO Portfolio - Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
  # push:
  #   branches:
  #     - main
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_SERVER_HOST }}
          username: ${{ secrets.BACKEND_SERVER_USERNAME }}
          key: ${{ secrets.BACKEND_SERVER_SECRETKEY }}
          port: ${{ secrets.BACKEND_SERVER_PORT }}
          script: |
            echo "Current directory is: $(pwd)"
            ls -al

          
      # - name: Checkout ${{ vars.USERNAME }}/poc-nodejs repository
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ vars.USERNAME }}/poc-nodejs
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     ref: ${{ inputs.branch }}
      #     path: ${{ vars.NODEJS_APP_NAME }}
      #     fetch-depth: 1
      #     submodules: false

      # - name: Create dir
      #   run: |
      #     if [ ! -d "${{ vars.NODEJS_APP_PATH }}" ]; then
      #         mkdir -p ${{ vars.NODEJS_APP_PATH }}
      #         echo "Directory created: ${{ vars.NODEJS_APP_PATH }}"
      #     fi
        
      # - name: Copy files to target dir
      #   run: |
      #     if [ -d "${{ vars.NODEJS_APP_PATH }}" ]; then
      #         cp -r $(pwd)/${{ vars.NODEJS_APP_NAME }}/* ${{ vars.NODEJS_APP_PATH }}/
      #         echo "Files copied to: ${{ vars.NODEJS_APP_PATH }}"
      #     else
      #         echo "Dir not found!! : ${{ vars.NODEJS_APP_PATH }}"
      #     fi
          
      # - name: Install package with npm
      #   run: |
      #     cd ${{ vars.NODEJS_APP_PATH }}
      #     npm install
        
      # - name: Start app!
      #   run: |
      #     pm2 delete all || true
      #     pm2 start ${{ vars.NODEJS_APP_PATH }}/index.js --name '${{ vars.NODEJS_APP_NAME }}'
      #     pm2 save
      #     sudo systemctl restart nginx
