name: Portfolio API - Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
      app-name:
        description: 'App name to deploy'
        required: true
        type: choice
        options:
          - 'go-portfolio-api'
      tag:
        description: 'Tag or version'
        required: true
        default: 'v0.1.0'
      build_app:
        description: 'Not run build step?'
        type: boolean
        default: false
  # push:
  #   branches:
  #     - main
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          
      - name: Checkout ${{ vars.USERNAME }}/${{ inputs.app-name }} repository
        if: ${{ !github.event.inputs.build_app }}
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app-name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.app-name }}
          fetch-depth: 1
          submodules: false

      - name: Build app...
        if: ${{ !github.event.inputs.build_app }}
        run: |
          cd ${{ inputs.app-name }}
          GOOS=linux GOARCH=amd64 GOMAXPROCS=1 go build -o ${{ inputs.app-name }}-app ./cmd/server/main.go
          mv ${{ inputs.app-name }}-app ../${{ inputs.app-name }}-app

      - name: Create zip file
        if: ${{ !github.event.inputs.build_app }}
        run: |
          zip ${{ inputs.app-name }}-app.zip ${{ inputs.app-name }}-app
          echo "Created ${{ inputs.app-name }}-app.zip"
    
      - name: Upload app to github packages
        if: ${{ !github.event.inputs.build_app }}
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app-name }}
          files: ${{ inputs.app-name }}-app.zip
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag_name: ${{ inputs.tag }}

      - name: Download github packages
        if: ${{ github.event.inputs.build_app }}
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app-name }}
          tag: ${{ inputs.tag }}
          fileName: ${{ inputs.app-name }}-app.zip
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Check if zip file exists
        run: |
          FILE_PATH="./${{ inputs.app-name }}-app.zip"
          if [ -f "$FILE_PATH" ]; then
            echo "✅ File '$FILE_PATH' found successfully!"
            ls -lh "$FILE_PATH"
          else
            echo "❌ Error: File '$FILE_PATH' not found!"
            exit 1
          fi  

      - name: List files
        run: |
          ls -la

      # - name: Unzip file
      #   run: |
      #     unzip -j ./${{ inputs.app-name }}-app.zip

      - name: Upload app to server
        run: |
          scp -r ./${{ inputs.app-name }}-app.zip ${{ vars.BACKEND_SERVER_USERNAME }}@${{ vars.BACKEND_SERVER_HOST }}:/home/${{ vars.GO_PORTFOLIO_API_USER}}
            