name: Portfolio API - Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
      app-name:
        description: 'App name to deploy'
        required: true
        type: choice
        options:
          - 'go-portfolio-api'
  # push:
  #   branches:
  #     - main
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          
      - name: Checkout ${{ vars.USERNAME }}/${{ inputs.app-name }} repository
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app-name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.app-name }}
          fetch-depth: 1
          submodules: false

      - name: Build App...
        run: |
          cd ${{ inputs.app-name }}
          GOOS=linux GOARCH=amd64 GOMAXPROCS=1 go build -o ${{ inputs.app-name }} ./cmd/server/main.go
          ls -la
          cd ..
          ls -la
          # mv ./${{ inputs.app-name }}/${{ inputs.app-name }} ${{ inputs.app-name }}

      - name: List files
        run: |
          ls -la

      # - name: 'Upload App to Artifact'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: backend-app
      #     path: ${{ inputs.app-name }}
      #     retention-days: 7
    
      # - name: Execute remote SSH commands using password
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.BACKEND_SERVER_HOST }}
      #     username: ${{ vars.BACKEND_SERVER_USERNAME }}
      #     key: ${{ secrets.BACKEND_SERVER_SECRETKEY }}
      #     port: ${{ secrets.BACKEND_SERVER_PORT }}
      #     script: |
      #       echo "Current directory is: $(pwd)"
      #       ls -al

          


      # - name: Create dir
      #   run: |
      #     if [ ! -d "${{ vars.NODEJS_APP_PATH }}" ]; then
      #         mkdir -p ${{ vars.NODEJS_APP_PATH }}
      #         echo "Directory created: ${{ vars.NODEJS_APP_PATH }}"
      #     fi
        
      # - name: Copy files to target dir
      #   run: |
      #     if [ -d "${{ vars.NODEJS_APP_PATH }}" ]; then
      #         cp -r $(pwd)/${{ vars.NODEJS_APP_NAME }}/* ${{ vars.NODEJS_APP_PATH }}/
      #         echo "Files copied to: ${{ vars.NODEJS_APP_PATH }}"
      #     else
      #         echo "Dir not found!! : ${{ vars.NODEJS_APP_PATH }}"
      #     fi
          
      # - name: Install package with npm
      #   run: |
      #     cd ${{ vars.NODEJS_APP_PATH }}
      #     npm install
        
      # - name: Start app!
      #   run: |
      #     pm2 delete all || true
      #     pm2 start ${{ vars.NODEJS_APP_PATH }}/index.js --name '${{ vars.NODEJS_APP_NAME }}'
      #     pm2 save
      #     sudo systemctl restart nginx
