name: Portfolio API - Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch app to pull'
        required: true
        default: 'main'
      app_name:
        description: 'App name to deploy'
        required: true
        type: choice
        options:
          - 'go-portfolio-api'
      tag:
        description: 'Tag or version'
        required: true
        default: 'v0.1.0'
      build_app:
        description: 'Not run build step?'
        type: boolean
        default: false
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          
      - name: Checkout ${{ vars.USERNAME }}/${{ inputs.app_name }} repository
        if: ${{ inputs.build_app == false }}
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app_name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.app_name }}
          fetch-depth: 1
          submodules: false

      - name: Build app...
        if: ${{ inputs.build_app == false }}
        run: |
          cd ${{ inputs.app_name }}
          GOOS=linux GOARCH=amd64 GOMAXPROCS=1 go build -o ${{ inputs.app_name }}-app ./cmd/server/main.go
          mv ${{ inputs.app_name }}-app ../${{ inputs.app_name }}-app

      - name: Create zip file
        if: ${{ inputs.build_app == false }}
        run: |
          zip ${{ inputs.app_name }}-app.zip ${{ inputs.app_name }}-app
          echo "Created ${{ inputs.app_name }}-app.zip"
    
      - name: Upload app to github packages
        if: ${{ inputs.build_app == false }}
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app_name }}
          files: ${{ inputs.app_name }}-app.zip
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag_name: ${{ inputs.tag }}

      - name: Download github packages
        if: ${{ inputs.build_app == true }}
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ vars.USERNAME }}/${{ inputs.app_name }}
          tag: ${{ inputs.tag }}
          fileName: ${{ inputs.app_name }}-app.zip
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Check if zip file exists
        run: |
          FILE_PATH="./${{ inputs.app_name }}-app.zip"
          if [ -f "$FILE_PATH" ]; then
            echo "✅ File '$FILE_PATH' found successfully!"
            ls -lh "$FILE_PATH"
          else
            echo "❌ Error: File '$FILE_PATH' not found!"
            exit 1
          fi

      - name: Build ENV file
        run: |
          echo "${{ secrets.GO_ENVIRONMENT_VARIABLE }}" > .env

      - name: List files
        run: |
          ls -la

      - name: clear app workspace on app server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BACKEND_SERVER_HOST }}
          username: ${{ secrets.BACKEND_SERVER_USERNAME }}
          key: ${{ secrets.BACKEND_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.BACKEND_SERVER_PORT }}
          script: |
            cd /home/${{ vars.GO_PORTFOLIO_API_USER}}
            rm ./${{ inputs.app_name }}-app .env

      - name: Upload file to app server
        run: |
          scp -r ./${{ inputs.app_name }}-app.zip ${{ vars.BACKEND_SERVER_USERNAME }}@${{ secrets.BACKEND_SERVER_HOST }}:/home/${{ vars.GO_PORTFOLIO_API_USER}}
          scp -r .env ${{ vars.BACKEND_SERVER_USERNAME }}@${{ secrets.BACKEND_SERVER_HOST }}:/home/${{ vars.GO_PORTFOLIO_API_USER}}

      - name: Unzip on app server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BACKEND_SERVER_HOST }}
          username: ${{ secrets.BACKEND_SERVER_USERNAME }}
          key: ${{ secrets.BACKEND_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.BACKEND_SERVER_PORT }}
          script: |
            cd /home/${{ vars.GO_PORTFOLIO_API_USER}}
            unzip -j ./${{ inputs.app_name }}-app.zip
            rm ./${{ inputs.app_name }}-app.zip
            ls -al