name: Setup SSH Server
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Server name to setup'
        required: true
        type: choice
        default: 'Back-End-Server'
        options:
          - 'Back-End-Server'
          - 'Front-End-Server'
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up runner workspace
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*

      - name: Create .ssh directory (if not exists)
        run: |
            if [ ! -d ~/.ssh ]; then
              mkdir -p ~/.ssh
              echo "Created ~/.ssh directory"
            else
              echo "~/.ssh already exists"
            fi

      - name: Write private key (Back End Server)
        if: ${{ inputs.server_name == 'Back-End-Server' }}
        run: |
          echo "${{ secrets.BACKEND_SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Write private key (Front End Server)
        if: ${{ inputs.server_name == 'Front-End-Server' }}
        run: |
          echo "${{ secrets.FRONTEND_SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Set permission for id_rsa
        run: |
          chmod 600 ~/.ssh/id_rsa

      - name: Scan SSH host key (Front End Server)
        if: ${{ inputs.server_name == 'Front-End-Server' }}
        run: |
          ssh-keyscan -H ${{ secrets.FRONTEND_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Scan SSH host key (Back End Server)
        if: ${{ inputs.server_name == 'Back-End-Server' }}
        run: |
          ssh-keyscan -H ${{ secrets.BACKEND_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Set permission for known_hosts
        run: |
          chmod 644 ~/.ssh/known_hosts

      - name: Clean up runner workspace
        if: always()
        run: |
          echo "Cleaning up temporary files..."
          rm -rf $(pwd)/*
          