
name: test-pipeline
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a add env
        run: |
          echo "PAC_ENV=Hello, GitHub Actions!" >> $GITHUB_ENV
          
      - name: Run a echo
        run: |
          echo "ENV : ${{ secrets.PERSONAL_ACCESS_TOKEN }}"
